### PR TITLE
Allow environment to override variables specified in tasks config and refine stdio handling

### PR DESCRIPTION
**Pull request by gabor-balla-emarsys**

### CODE REVIEW

**Comment by drawain** [comment]
@gabor-balla-emarsys @blacksonic Isn't it a breaking change? If someone (accidentally) set an OS level or other env variable from outside of the application in the config, from now it works different and the override will be applied!

**Comment by sonicoder86** [comment]
Is it a real use case for us?

**Comment by drawain** [comment]
It doesn't matter I think. If it's true and it could be possible somewhere what I said then it's a breaking change :)

**Comment by sonicoder86** [comment]
Well then bump a major with the harmony flag removal

**Pull request merged**
