### PR TITLE
refactor(test): run mocha bin using npm built in function

### PR DESCRIPTION
**Pull request by bankyadam**

### CODE REVIEW

**Comment by jzsfkzm** [comment]
Looks good to me

**Comment by drawain** [comment]
Is it works if the project doesn't contains a local mocha installation? 
Now it uses the mocha from the boar-tasks-server library, but after the modification it seems that it will use the local mocha - but it's not necessary to have it in your project directly. After all, if it works I think it is the same as using a single "mocha" command because the local node_modules/.bin path is bound to the project directory context.

**Comment by bankyadam** [comment]
@drawain boar-task-server has mocha as dependency, so it'll be there as local. Before this modification, it tried to run from the local node_modules folder also, so it depended on a local representation of mocha bin. But with this relative call, boar-task-server will not work with npm v3, since it has a flat directory structure.

**Comment by drawain** [comment]
Yes, thats true for npm3 but not for npm2. So I think this change will be incompatible with npm2 :)

**Comment by bankyadam** [comment]
@drawain true, I'm looking for cross-version solution

**Comment by jzsfkzm** [comment]
Doesn't look good to me any more

**Comment by bankyadam** [comment]
I've added a new solution and tested with npm2 and npm3.

**Pull request merged**
